/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ReportRouteImport } from './routes/report'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInvestigateRouteImport } from './routes/api/investigate'
import { Route as ApiKnowledgeRouteImport } from './routes/api/knowledge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestigateRoute = ApiInvestigateRouteImport.update({
  id: '/api/investigate',
  path: '/api/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeRoute = ApiKnowledgeRouteImport.update({
  id: '/api/knowledge',
  path: '/api/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
  '/report': typeof ReportRoute
  '/workflow': typeof WorkflowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/knowledge': typeof ApiKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
  '/report': typeof ReportRoute
  '/workflow': typeof WorkflowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/knowledge': typeof ApiKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investigate': typeof InvestigateRoute
  '/knowledge': typeof KnowledgeRoute
  '/report': typeof ReportRoute
  '/workflow': typeof WorkflowRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investigate': typeof ApiInvestigateRoute
  '/api/knowledge': typeof ApiKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investigate'
    | '/knowledge'
    | '/report'
    | '/workflow'
    | '/api/health'
    | '/api/investigate'
    | '/api/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investigate'
    | '/knowledge'
    | '/report'
    | '/workflow'
    | '/api/health'
    | '/api/investigate'
    | '/api/knowledge'
  id:
    | '__root__'
    | '/'
    | '/investigate'
    | '/knowledge'
    | '/report'
    | '/workflow'
    | '/api/health'
    | '/api/investigate'
    | '/api/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestigateRoute: typeof InvestigateRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ReportRoute: typeof ReportRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInvestigateRoute: typeof ApiInvestigateRoute
  ApiKnowledgeRoute: typeof ApiKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investigate': {
      id: '/api/investigate'
      path: '/api/investigate'
      fullPath: '/api/investigate'
      preLoaderRoute: typeof ApiInvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge': {
      id: '/api/knowledge'
      path: '/api/knowledge'
      fullPath: '/api/knowledge'
      preLoaderRoute: typeof ApiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestigateRoute: InvestigateRoute,
  KnowledgeRoute: KnowledgeRoute,
  ReportRoute: ReportRoute,
  WorkflowRoute: WorkflowRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInvestigateRoute: ApiInvestigateRoute,
  ApiKnowledgeRoute: ApiKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
